name: champion_alerts
description: A starting point for Dart libraries or applications.
version: 0.0.1
repository: https://github.com/cotw-fabier/champion_alerts

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  change_notifier: ^0.28.0 #reimplementation of ChangeNotifier to split it out from Flutter Foundation.
  uuid: ^4.5.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
